- root/src/admin/groups/index.tt
- root/src/admin/members/index.tt
- root/static/css/admin.css
This'll fix the double-toasts.
> Re-work JS to fix multiple event fires.

- lib/HiveWeb/Controller/Member.pm
- root/src/admin/members.tt
The column has already been marked as unique in the database.
> Unique handle

- lib/HiveWeb.pm
- lib/HiveWeb/Controller/Root.pm
If someone not logged in gets an access denied, return him to that page upon login.
> Better access denied handling

- hiveweb.pl
- lib/HiveWeb/Controller/API/Admin/Storage.pm
- lib/HiveWeb/Schema/Result/StorageSlot.pm
- root/src/email/assigned_slot_plain.tt
- root/static/js/jquery.contextmenu.js
Also fixes bug where the context menu pops under a dialogue.
> Send storage email

- lib/HiveWeb/Controller/API/Temperature.pm
This'll stop a fair bit of data transfer from the SQL server to the client.
> Limit the rows to one in SQL.

- root/src/admin/members.tt
> Try out an improved mobile layout.

- lib/HiveWeb/Controller/API.pm
- lib/HiveWeb/Controller/API/Soda.pm
- lib/HiveWeb/Schema/Result/SodaStatus.pm
- lib/HiveWeb/Schema/Result/SodaType.pm
- root/src/index.tt
- root/static/css/main.css
- root/static/js/panels.js
Show the state of the soda machine!
Resolves #97.
> Hive status

- lib/HiveWeb/Controller/API/Admin/Members.pm
- lib/HiveWeb/Controller/Member.pm
- lib/HiveWeb/Schema/Result/Member.pm
- root/src/admin/members.tt
- root/src/member/profile.tt
> Tel field upgrade

- lib/HiveWeb/Controller/API/Admin/Images.pm
- lib/HiveWeb/Controller/API/Admin/Members.pm
- lib/HiveWeb/Controller/Admin/Images.pm
- lib/HiveWeb/Schema/Result/Image.pm
- root/src/admin/members.tt
Resolves #104.  Also adds in thumbnail feature.
> Add image rotate

- lib/HiveWeb/Controller/API/Admin/AccessLog.pm
- root/src/admin/access_log.tt
> Add in fname and lname search.

- root/src/admin/curses.tt
- root/src/admin/members.tt
- root/src/forgot.tt
- root/src/member/profile.tt
- root/src/member/register.tt
> Use HTML5 input types.

- lib/HiveWeb/Controller/API/Admin/Members.pm
- root/src/admin/members.tt
> Add in badge search option.

- lib/HiveWeb/Controller/API/Admin/Storage.pm
- lib/HiveWeb/Schema/Result/StorageLocation.pm
- lib/HiveWeb/Schema/Result/StorageSlot.pm
- root/src/admin/storage.tt
> Sort order to slots

- lib/HiveWeb/Schema/Result/Application.pm
- lib/HiveWeb/Schema/Result/Member.pm
Add in the DBIx code for the application table.
> Add application table

- lib/HiveWeb/Controller/API/Application.pm
- lib/HiveWeb/Controller/API/Image.pm
- lib/HiveWeb/Schema/Result/Image.pm
- root/src/index.tt
- root/static/css/main.css
- root/static/js/panels.js
- root/static/js/user_panels.js
Provide a panel for pending applicants that shows the status of their application and what they still need to do.
> Show application state

- root/static/js/picture_dialogue.js
- root/static/js/user_panels.js
> Picture uploading library #2

- lib/HiveWeb/Controller/API/Admin/Applications.pm
- root/static/js/admin_panels.js
> Allow finalizing applications

- README.md
- lib/HiveWeb/Controller/API/Application.pm
- lib/HiveWeb/Controller/Application.pm
- root/static/js/admin_panels.js
- root/static/js/user_panels.js
> Print application

- bin/delete_orphaned_images.pl
> Delete orphaned images

- README.md
- lib/HiveWeb/Controller/API/Member.pm
- lib/HiveWeb/Controller/Member.pm
- lib/HiveWeb/Controller/Root.pm
- lib/HiveWeb/Schema/Result/Member.pm
- root/src/member/profile.tt
- root/src/two_factor.tt
- root/src/wrapper.tt
> Two factor authentication

- lib/HiveWeb.pm
- lib/HiveWeb/Controller/Member.pm
> Fix payment link access

- lib/HiveWeb.pm
- lib/HiveWeb/Controller/Application.pm
- lib/HiveWeb/Controller/Root.pm
- root/src/application/edit.tt
Various things that shook out when releasing Membership Applications into the wild.
> Fix application issues

- less/src/utility.less
- lib/HiveWeb/Controller/API/Admin/Applications.pm
- root/static/js/admin_panels.js
> Finalize application actions

- bin/queue_runner.pl
- hiveweb.pl
- lib/HiveWeb/Controller/Storage.pm
- lib/HiveWeb/Schema/Result/StorageSlot.pm
> Send messages when storage requests happen.

- lib/HiveWeb/Controller/API/Admin/Storage.pm
- lib/HiveWeb/Schema/Result/StorageLocation.pm
- root/src/admin/storage.tt
> Storage location sort

- lib/HiveWeb/Controller/API/Admin/Storage.pm
- root/src/admin/storage.tt
> Storage delete

- lib/HiveWeb/Controller/API/Admin/Curses.pm
- lib/HiveWeb/Controller/Admin.pm
- root/src/admin/curses.tt
> Filter curses

- lib/HiveWeb/Controller/Root.pm
- lib/HiveWeb/DBIx/Class/Core.pm
- lib/HiveWeb/Schema/Result/Curse.pm
- lib/HiveWeb/Schema/Result/Lamp.pm
- lib/HiveWeb/Schema/Result/Member.pm
- lib/HiveWeb/Schema/Result/MemberCurse.pm
- lib/HiveWeb/Schema/Result/StorageRequest.pm
- root/static/js/user_panels.js
> Add overloaded class when admin to expand TO_JSON

- lib/HiveWeb/Controller/API/Admin/Members.pm
- root/static/js/pages/admin_members.js
> Fix admin js

- root/static/js/admin_panels.js
- root/static/js/picture_dialogue.js
> Add photo zero state

- root/static/js/api.js
- root/static/js/pages/admin_members.js
- root/static/js/pages/admin_storage.js
> Fix keyboard shortcuts

- lib/HiveWeb/Controller/API/Admin/Applications.pm
- lib/HiveWeb/Controller/API/Admin/Members.pm
- root/src/admin/members.tt
- root/src/wrapper.tt
- root/static/js/admin_panels.js
- root/static/js/badge_editor.js
- root/static/js/pages/admin_members.js
Resolves #208 
- Changes badge edit on member edit page to propose changes that are actually done when OK is hit.
- Adds in warning if you close member edit page without saving.
- Adds in badge entry option on accepting member.
> Add badge on app complete

- hiveweb.pl
- lib/HiveWeb/Controller/API/Admin/Applications.pm
- root/src/email/application/finalize_plain.tt
> Send finalize e-mail

- dbicdh/PostgreSQL/deploy/5/001-auto.sql
- dbicdh/PostgreSQL/upgrade/4-5/001-auto.sql
- dbicdh/_source/deploy/5/001-auto.yml
- lib/HiveWeb/Controller/API/Admin/Members.pm
- lib/HiveWeb/Schema/Result/Badge.pm
- lib/HiveWeb/Schema/Result/Member.pm
- root/src/admin/members.tt
- root/static/js/pages/admin_members.js
There's no UI for linking account yet, but the underlying structure is done.
Resolves #229.
> Linked member structure

- bin/expire_memberships.pl
- dbicdh/PostgreSQL/deploy/5/001-auto.sql
- dbicdh/PostgreSQL/initialize/5/001-add-groups.sql
- dbicdh/PostgreSQL/upgrade/4-5/001-auto.sql
- dbicdh/_source/deploy/5/001-auto.yml
- hiveweb.pl
- lib/HiveWeb/Controller/API/Admin/Applications.pm
- lib/HiveWeb/Controller/API/Admin/Groups.pm
- lib/HiveWeb/Controller/API/Admin/Members.pm
- lib/HiveWeb/Schema/Result/AuditLog.pm
- lib/HiveWeb/Schema/Result/Member.pm
Script to cancel the expiring memberships.
Resolves #222.
> Cancel expiring memberships

- bin/queue_runner.pl
- dbicdh/PostgreSQL/deploy/5/001-auto.sql
- dbicdh/PostgreSQL/upgrade/4-5/001-auto.sql
- dbicdh/_source/deploy/5/001-auto.yml
- hiveweb.pl
- lib/HiveWeb/Controller/PayPal.pm
- lib/HiveWeb/Schema/Result/Payment.pm
- root/src/email/application/pay_plain.tt
- root/src/email/welcome_plain.tt
> Handle Payment Received Messages

- root/src/email/application/finalize_plain.tt
> Fix errors.

- bin/expire_memberships.pl
- bin/queue_runner.pl
- dbicdh/PostgreSQL/deploy/5/001-auto.sql
- dbicdh/PostgreSQL/initialize/5/001-add-groups.sql
- dbicdh/PostgreSQL/initialize/5/002-add-survey.sql
- dbicdh/PostgreSQL/upgrade/4-5/001-auto.sql
- dbicdh/_source/deploy/5/001-auto.yml
- hiveweb.pl
- lib/HiveWeb/Controller/Member.pm
- lib/HiveWeb/Schema/Result/Member.pm
- lib/HiveWeb/Schema/Result/Survey.pm
- lib/HiveWeb/Schema/Result/SurveyAnswer.pm
- lib/HiveWeb/Schema/Result/SurveyQuestion.pm
- lib/HiveWeb/Schema/Result/SurveyResponse.pm
- root/src/email/member/notify_term_plain.tt
- root/src/member/cancel.tt
> Cancellation page

- lib/HiveWeb/Controller/API/Admin/Members.pm
- lib/HiveWeb/Schema/Result/Member.pm
- root/src/admin/members.tt
- root/src/wrapper.tt
- root/static/js/admin_panels.js
- root/static/js/editor.js
- root/static/js/pages/admin_members.js
This way, admins can do and undo links.
> Add link UI

- lib/HiveWeb/Controller/API/Admin/Members.pm
- root/static/js/pages/admin_members.js
> Fix null warnings.

- lib/HiveWeb/Controller/API.pm
> Fix undefined warning.

- lib/HiveWeb/Controller/API/Admin/Members.pm
- root/static/js/editor.js
> Fail if you attempt to link an account to itself.

- bin/deploy.pl
- dbicdh/PostgreSQL/deploy/7/001-auto.sql
- dbicdh/PostgreSQL/upgrade/-1-7/001-auto.sql
- dbicdh/PostgreSQL/upgrade/6-7/001-auto.sql
- dbicdh/_source/deploy/7/001-auto.yml
- lib/HiveWeb/Schema.pm
- lib/HiveWeb/Schema/Result/Application.pm
- root/src/application/edit.tt
- root/src/email/application/created_plain.tt
> Who signed you up

- root/static/js/pages/admin_groups.js
> Fix leftover TT cruft.

- hiveweb.pl
- lib/HiveWeb/Controller/PayPal.pm
> Send Slack invites

- root/static/js/picture_dialogue.js
> Add in enlarge option.

- lib/HiveWeb/Controller/Root.pm
Before it was not associating members to right user & wrong password.
> Hunt for user to log bad password.

- less/src/admin.less
- root/static/js/admin_panels.js
- root/static/js/panels.js
There are enough that it's scrolling the screen too much.
> Collapse applications

- root/static/js/admin_panels.js
Add in an Accept Picture icon.
> Accept picture

- less/src/admin.less
- less/src/reports.less
- lib/HiveWeb/Controller/Admin/Reports.pm
- root/src/admin/index.tt
- root/src/admin/reports/index.tt
- root/src/admin/reports/member.tt
> Member Report

- bin/paypal_refresh.pl
- dbicdh/PostgreSQL/deploy/9/001-auto.sql
- dbicdh/PostgreSQL/upgrade/8-9/001-auto.sql
- dbicdh/_source/deploy/9/001-auto.yml
- lib/HiveWeb/Controller/PayPal.pm
- lib/HiveWeb/Schema.pm
- lib/HiveWeb/Schema/Result/Log.pm
- lib/HiveWeb/Schema/ResultSet/IPNMessage.pm
- lib/HiveWeb/Schema/ResultSet/Log.pm
Move common code to a ResultSet - greatly simplifies everything.
> Clean up IPN handling

- lib/HiveWeb/Schema/Result/Application.pm
> Auto-update the application

- less/src/reports.less
- less/src/utility.less
- lib/HiveWeb/Controller/API/Admin/Reports.pm
- lib/HiveWeb/Controller/Admin/Reports.pm
- lib/HiveWeb/DBIx/Class/ResultSet.pm
- lib/HiveWeb/Schema/Result/Payment.pm
- lib/HiveWeb/Schema/ResultSet/Member.pm
- root/src/admin/reports/index.tt
- root/src/admin/reports/membership.tt
> Monthly Membership Report

- lib/HiveWeb/Schema/Result/IPNMessage.pm
> Use add/remove methods for groups

- bin/convert_pdf_images.pl
- root/static/js/picture_dialogue.js
Resolves #132.
Actually bans PDFs.
> Converter tool.

- lib/HiveWeb/Controller/API/Admin/Reports.pm
- lib/HiveWeb/Controller/Admin/Reports.pm
- lib/HiveWeb/Controller/PayPal.pm
- lib/HiveWeb/Schema/Result/IPNMessage.pm
> Use the Serializer tool.

- bin/expire_memberships.pl
- bin/storage_renewals.pl
- lib/HiveWeb/Controller/API/Admin/Applications.pm
- lib/HiveWeb/Controller/API/Admin/Groups.pm
- lib/HiveWeb/Controller/API/Admin/Members.pm
- lib/HiveWeb/Controller/API/Admin/Storage.pm
- lib/HiveWeb/Controller/API/Application.pm
- lib/HiveWeb/Controller/API/Storage.pm
- lib/HiveWeb/Controller/Application.pm
- lib/HiveWeb/Controller/Member.pm
- lib/HiveWeb/Schema/Result/Action.pm
- lib/HiveWeb/Schema/Result/Application.pm
- lib/HiveWeb/Schema/Result/AuditLog.pm
- lib/HiveWeb/Schema/Result/Badge.pm
- lib/HiveWeb/Schema/Result/IPNMessage.pm
- lib/HiveWeb/Schema/Result/Member.pm
- lib/HiveWeb/Schema/Result/StorageRequest.pm
- lib/HiveWeb/Schema/Result/StorageSlot.pm
> Audit trails

- bin/expire_memberships.pl
- bin/queue_runner.pl
- bin/storage_renewals.pl
- lib/HiveWeb/Controller/API/Admin/Applications.pm
- lib/HiveWeb/Controller/API/Admin/Groups.pm
- lib/HiveWeb/Controller/API/Admin/Members.pm
- lib/HiveWeb/Controller/API/Admin/Storage.pm
- lib/HiveWeb/Controller/Application.pm
- lib/HiveWeb/Controller/Member.pm
- lib/HiveWeb/Schema/Result/IPNMessage.pm
- lib/HiveWeb/Schema/Result/Member.pm
> Group add remove improvement

- dbicdh/PostgreSQL/deploy/13/001-auto.sql
- dbicdh/PostgreSQL/initialize/13/001-air-compressor.sql
- dbicdh/PostgreSQL/upgrade/12-13/001-auto.sql
- dbicdh/_source/deploy/13/001-auto.yml
- lib/HiveWeb/Schema.pm
- lib/HiveWeb/Schema/Result/Item.pm
- lib/HiveWeb/Schema/Result/TempLog.pm
- root/static/js/panels.js
We're now measuring things besides temperatures. (Isn't that cool?)
> Add units to items

- .perlcriticrc
- hiveweb.pl
- lib/HiveWeb/Controller/API/Access.pm
- lib/HiveWeb/Controller/API/Admin/AccessLog.pm
- lib/HiveWeb/Schema.pm
- lib/HiveWeb/Schema/Result/AccessLog.pm
Add code so the Arduini can query intweb and figure out when quiet hours are.
> Quiet hours

- dbicdh/PostgreSQL/deploy/14/001-auto.sql
- dbicdh/PostgreSQL/upgrade/13-14/001-auto.sql
- dbicdh/_source/deploy/14/001-auto.yml
- lib/HiveWeb/Schema.pm
- lib/HiveWeb/Schema/Result/Application.pm
- lib/HiveWeb/Schema/Result/Member.pm
- lib/HiveWeb/Schema/Result/ResetToken.pm
> Fix timestamp

- root/static/js/board_panels.js
- root/static/js/pages/admin_storage.js
- root/static/js/panels.js
> Fix panels

- hiveweb.pl
- lib/HiveWeb/Schema/Result/IPNMessage.pm
> Remove late payment groups.

- bin/expire_memberships.pl
- bin/report_emailer.pl
> Fix the pathing problems.

- lib/HiveWeb/Schema/Result/StorageSlot.pm
- root/static/js/pages/admin_storage.js
This is more like what you want.
> Mark unrequestable slots as used.

- lib/HiveWeb/Controller/API/Admin/Members.pm
- root/src/admin/members.tt
- root/static/js/pages/admin_members.js
> Link search

- lib/HiveWeb/Controller/Member.pm
- lib/HiveWeb/Controller/Root.pm
> trim whitespace from beginning and end of email address in form fields
